### PR TITLE
Remove ComposeSmsActivity from AndroidManifest.xml

### PR DESCRIPTION
**Pull request by alxndrsn**
This activity is not in the current codebase.

Fix for #405

### CODE REVIEW

**Comment by eyedol** [comment]
True. For some reason the OS requires it to make the app the default SMS app on the device.

**Comment by alxndrsn** [comment]
I guess this is the same as https://github.com/ushahidi/SMSSync/pull/394#issuecomment-213209365

Would you consider a PR with comments in the `AndroidManifest.xml` to explain this?

**Comment by eyedol** [comment]
Yes. Clever!

**Comment by eyedol** [comment]
Closing. This has been addressed in `PR` #442

**Pull request closed without merging**
